package com.hwk.studyapp.dao;

import java.util.List;

import com.hwk.studyapp.entity.Userinfo;

public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    int insertSelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    Userinfo selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    int updateByPrimaryKeySelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    int updateByPrimaryKey(Userinfo record);

	List<Userinfo> selectUserinfoList(Userinfo userinfo);
    
}