package com.hwk.studyapp.entity;

import java.util.Date;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.uid
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.upw
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    private String upw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.urole
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    private String urole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.uname
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.mskill
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    private String mskill;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.mstarttime
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    private Date mstarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.mendtime
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    private Date mendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.mrates
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    private Integer mrates;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.mamount
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    private Integer mamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.astatus
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    private String astatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.commone
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    private String commone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.commtwo
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    private String commtwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.uid
     *
     * @return the value of userinfo.uid
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.uid
     *
     * @param uid the value for userinfo.uid
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.upw
     *
     * @return the value of userinfo.upw
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public String getUpw() {
        return upw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.upw
     *
     * @param upw the value for userinfo.upw
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public void setUpw(String upw) {
        this.upw = upw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.urole
     *
     * @return the value of userinfo.urole
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public String getUrole() {
        return urole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.urole
     *
     * @param urole the value for userinfo.urole
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public void setUrole(String urole) {
        this.urole = urole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.uname
     *
     * @return the value of userinfo.uname
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.uname
     *
     * @param uname the value for userinfo.uname
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.mskill
     *
     * @return the value of userinfo.mskill
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public String getMskill() {
        return mskill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.mskill
     *
     * @param mskill the value for userinfo.mskill
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public void setMskill(String mskill) {
        this.mskill = mskill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.mstarttime
     *
     * @return the value of userinfo.mstarttime
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public Date getMstarttime() {
        return mstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.mstarttime
     *
     * @param mstarttime the value for userinfo.mstarttime
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public void setMstarttime(Date mstarttime) {
        this.mstarttime = mstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.mendtime
     *
     * @return the value of userinfo.mendtime
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public Date getMendtime() {
        return mendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.mendtime
     *
     * @param mendtime the value for userinfo.mendtime
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public void setMendtime(Date mendtime) {
        this.mendtime = mendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.mrates
     *
     * @return the value of userinfo.mrates
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public Integer getMrates() {
        return mrates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.mrates
     *
     * @param mrates the value for userinfo.mrates
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public void setMrates(Integer mrates) {
        this.mrates = mrates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.mamount
     *
     * @return the value of userinfo.mamount
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public Integer getMamount() {
        return mamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.mamount
     *
     * @param mamount the value for userinfo.mamount
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public void setMamount(Integer mamount) {
        this.mamount = mamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.astatus
     *
     * @return the value of userinfo.astatus
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public String getAstatus() {
        return astatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.astatus
     *
     * @param astatus the value for userinfo.astatus
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public void setAstatus(String astatus) {
        this.astatus = astatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.commone
     *
     * @return the value of userinfo.commone
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public String getCommone() {
        return commone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.commone
     *
     * @param commone the value for userinfo.commone
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public void setCommone(String commone) {
        this.commone = commone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.commtwo
     *
     * @return the value of userinfo.commtwo
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public String getCommtwo() {
        return commtwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.commtwo
     *
     * @param commtwo the value for userinfo.commtwo
     *
     * @mbg.generated Sun Nov 10 19:54:54 CST 2019
     */
    public void setCommtwo(String commtwo) {
        this.commtwo = commtwo;
    }
}